server:
  port: 8073

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myuser
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: Food

springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui.html